### ISSUE TITLE
Design File Refactor

### ISSUE THREAD

**Issue by kocheck** [GitHawkApp/Design-Resources#2]
## Overview 
I have been doing some thinking about Githawk and had an idea for the design repo to talk about if you are all up for it! 

I would like to suggest a refactor the design files for Githawk. _The goals for this update are;_
- An easier system to submit PR requests. And track changes to files in git.
- icon update, The tab bar icons are not pixel perfect. 
- Rebuild missing screens
- Refactor/Rename @kocheck sketch symbols from PR #1 to work more efficiently within the current design system. 

## Proposed Implementation 
```
- app.sketch (Library)
    ↳ Screens.folder
       - Inbox.sketch
           - Issue.sketch 
       - Search.sketch
           - Repo.sketch
       - Bookmarks.sketch
       - Profile.sketch
       - Settings.sketch 
       - Clickable-Prototype.sketch
- icons PSD
- App-Icon.psd
- REAME.md
```
### App Library 
`app.sketch` becomes the master sketch library file. All master symbols, icons, colors, and type treatments would live here. 

The idea is that as a change to a global UI component is approved and added to the `app.sketch`. file. These changes would trickle down to the different screens. Making smaller changes to the app more trackable. 

### App Screen Breakout 
Breaking out the different screens would make me less nervous as each branch and PR wouldn't be replacing the entirety of the design file each time. Allowing for quick iterations on branches that would (hopefully) be more tractable and easier to maintain. **What do ya'll think?**

Any ideas, to make this better? @rnystrom If you think this would be helpful I think I might work on this next. 👍

**Comment by rnystrom** [comment]
Love every bit of it. I’ve never done any collab with Sketch so I’d love to learn some best practices!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kocheck** [comment]
Sounds like fun! I think best practices working with sketch in a git repo is still very new. Maybe after Githawk has a good flow is going we should write a Medium article and help set more public concrete Best practices. 😆 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kocheck** [comment]
Hey @rnystrom clearing out old tickets assigned to me. I think we can safely close this 😆
